# -*- coding: utf-8 -*-
"""site.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14K0FU9LgoWAPkmFmkKRNSKgIatTImf34
"""
web: gunicorn site:app
!pip install dash

from dash import Dash, html, dcc, Input, Output, dash_table
import plotly.express as px
import pandas as pd
import os
from google.colab import drive

drive.mount("/content/drive", force_remount=True)

os.environ.get('KEY')

# Replace the folder URL with the direct link to the Excel file
arquivo_excel = "/content/drive/MyDrive/ProjetoEmpresa/empresa.xlsx"
df = pd.read_excel(arquivo_excel)

# Adicione uma nova coluna 'Estacao' com base nas datas fornecidas
def classificar_estacao(data):
    if (data.month == 12 and data.day >= 23) or (data.month == 1) or (data.month == 2) or (data.month == 3 and data.day <= 20):
        return 'verao'
    elif (data.month == 3 and data.day >= 21) or (data.month == 4) or (data.month == 5) or (data.month == 6 and data.day <= 21):
        return 'outono'
    elif (data.month == 6 and data.day >= 22) or (data.month == 7) or (data.month == 8) or (data.month == 9 and data.day <= 23):
        return 'inverno'
    elif (data.month == 9 and data.day >= 24) or (data.month == 10) or (data.month == 11) or (data.month == 12 and data.day <= 22):
        return 'primavera'
    else:
        return 'desconhecido'  # Lidando com datas fora desses intervalos

df['Estacao'] = df['Data'].apply(classificar_estacao)

app = Dash(__name__)

# Creating the scatter plot for "Relação de Data e Serviço Realizado" (calendário)
fig_calendario = px.scatter(df, x="Data", y="ServicoRealizado", color="Funcionario")
fig_calendario.update_layout(
    xaxis=dict(
        dtick="M1",  # Um tick a cada mês
        tickformat="%b\n%Y",  # Formato da data no eixo x
    ),
    yaxis=dict(
        title="Serviço Realizado"
    )
)

# Get unique values of 'Cliente' for dropdown options
opcoes_lojas = list(df['Cliente'].unique())
opcoes_lojas.append("Todos os Clientes")

# Dropdown options for different types of graphs
opcoes_graficos = [
    {'label': 'Serviços Realizados por Funcionário (Todos os Clientes)', 'value': 'grafico_funcionarios'},
    {'label': 'Horas por Serviço de Cada Funcionário', 'value': 'grafico_horas_servico_funcionario'},
    {'label': 'Relação de Data e Serviço Realizado (Calendário)', 'value': 'grafico_calendario'},
    # Adicione outras opções conforme necessário
]

# Dropdown options for seasons
opcoes_estacoes = [
    {'label': 'Verão', 'value': 'verao'},
    {'label': 'Outono', 'value': 'outono'},
    {'label': 'Inverno', 'value': 'inverno'},
    {'label': 'Primavera', 'value': 'primavera'},
]

app.layout = html.Div(children=[
    html.H1(children='Serviços das Lojas'),
    html.H2(children='Gráficos e Tabela com os Serviços Realizados'),
    html.Div(children='''
        Obs: Estes gráficos e tabela mostram diferentes aspectos dos serviços realizados.
    '''),

    dcc.Dropdown(options=opcoes_graficos, value='grafico_calendario', id='tipo_grafico'),

    dcc.Graph(
        id='grafico',
        figure=fig_calendario  # Gráfico padrão ao iniciar o aplicativo
    ),

    dcc.Dropdown(options=opcoes_estacoes, value=['verao'], id='estacao_dropdown', multi=True),

    dash_table.DataTable(
        id='tabela',
        columns=[
            {"name": col, "id": col} for col in df.columns
        ],
        style_table={'overflowX': 'auto'},
    )
])

@app.callback(
    [Output('grafico', 'figure'),
     Output('tabela', 'data')],
    [Input('tipo_grafico', 'value'),
     Input('estacao_dropdown', 'value')]
)
def update_output(tipo_grafico, estacoes_selecionadas):
    if tipo_grafico == 'grafico_funcionarios':
        fig = px.bar(df, y="ServicoRealizado", x="Funcionario", color="Cliente", barmode="group")
        tabela_data = df[['Funcionario', 'ServicoRealizado', 'Cliente']].to_dict('records')
    elif tipo_grafico == 'grafico_horas_servico_funcionario':
        fig = px.bar(df, y="HoraTrab", x="Funcionario", color="ServicoRealizado", barmode="group")
        tabela_data = df[['Funcionario', 'HoraTrab', 'ServicoRealizado']].to_dict('records')
    elif tipo_grafico == 'grafico_calendario':
        if not estacoes_selecionadas:  # Se nenhuma estação for selecionada, use todas
            tabela_data = df[['Data', 'ServicoRealizado', 'Funcionario']].to_dict('records')
            fig = fig_calendario
        else:
            # Filtra o DataFrame para incluir apenas as estações selecionadas
            df_filtrado = df[df['Estacao'].isin(estacoes_selecionadas)]
            fig = px.scatter(df_filtrado, x="Data", y="ServicoRealizado", color="Funcionario")
            fig.update_layout(
                xaxis=dict(dtick="M1", tickformat="%b\n%Y"),
                yaxis=dict(title="Serviço Realizado")
            )
            tabela_data = df_filtrado[['Data', 'ServicoRealizado', 'Funcionario']].to_dict('records')
    # Adicione outras opções conforme necessário

    return fig, tabela_data

if __name__ == '__main__':
    app.run_server(debug=True)
